#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config focused_border_color	      "#ffb86c"
bspc config active_border_color	          "#50fa7b"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

variety &
picom -f & 
xsetroot -cursor_name left_ptr &
#nitrogen --restore &
dunst &
nm-applet &
volumeicon &
numlockx on &
#/usr/lib/polkit-1-gnome/polkit-gnome-authentication-agent-1 &
#blueman-tray &
lxpolkit &
~/.config/polybar/launch.sh &
